### ISSUE TITLE
LogCapturing tool isn't in bootstrap-test-play-28

### ISSUE THREAD

**Issue by peckover** [hmrc/bootstrap-play#49]
LogCapturing tool has been moved to bootstrap-test-play-26 but isn't in bootstrap-test-play-28 causing test compilation failures after play upgrade

**Comment by peckoverHMRC** [comment]
PR raised to copy it over https://github.com/hmrc/bootstrap-play/pull/50

**Comment by MJCallahanPage** [comment]
Is anyone able to merge this PR above? We have to keep manually copying this over and this PR has been ready since May...

**Comment by colin-lamed** [comment]
This has been resolved by #74
